import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

const font = Jost({
  weight: ["200", "300", "400", "600"],
  subsets: ["latin"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
